#source 'https://github.com/CoolPrince/PrivatePods.git'
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TestModularization_A_Extension_Example' do
  pod 'TestModularization_A_Extension', :path => '../'

  target 'TestModularization_A_Extension_Tests' do
    inherit! :search_paths

    pod "CTMediator"

  end
end
