use_frameworks!

target 'TestModularization_A_Extension_Example' do
  pod 'TestModularization_A_Extension', :path => '../'

  target 'TestModularization_A_Extension_Tests' do
    inherit! :search_paths

    
  end
end
