source 'https://github.com/ModulizationDemo/PrivatePods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TestModularization_A_Extension_Example' do
  pod 'TestModularization_A_Extension', :path => '../'
  pod "CTMediator"

  target 'TestModularization_A_Extension_Tests' do
    inherit! :search_paths

    
  end
end
